### ISSUE TITLE
Need Help Downgrading

### ISSUE THREAD

**Issue by TickleMaPickl3** [The-1-7-10-Pack/The-1.7.10-Pack#113]
Hey An Amazing Mod.
Just like in this post :https://github.com/The-1-7-10-Pack/The-1.7.10-Pack/issues/107#issuecomment-71376161 - i accidentally updated, i would like to downgrade it could u please link me a download or something.
p.s. i play on a friends server and after the update i get this http://gyazo.com/3c9465e4bc756e43a76a4553f8c87a3f
&
http://gyazo.com/f33ee188023a28f2f7c725a2ec929d5a - when i press join
Moreover when i open the launcher it looks like this: http://gyazo.com/5bfabc53e830b16ed3be80516f9227d2 i do not know if this modpack has anything to do with it but, it went haywire after the update.
iv also given it [7GB] & re-installed modpack/launcher & changed java & done all the crap i can find.
PLEASE HELP ;'[

**Comment by daytimepanther** [comment]
Well the first two screenshots show that the server is using a different version of the pack you are using. The last screenshot is just the Technic Platform being weird because they had some problems today. As for upgrading I don't think you really can. I really wish the modpack author would consider using Solder but I can't really help that. Anyway, the only way to fix the problem would be to first, tell your friend to backup all of the server files (just in case). Then he needs to update the server and everything should be good.

**Comment by TickleMaPickl3** [comment]
okay thank you, one extra question.... what if i grabbed his mods file and replaced it with mine?

**Comment by daytimepanther** [comment]
Yeah that would work get his config files too or you might run into issues.

**Comment by TickleMaPickl3** [comment]
okay thank you for your help DTP

**Comment by TickleMaPickl3** [comment]
how does one close this issue

**Comment by daytimepanther** [comment]
I'm not sure the contributors of the pack might be the only ones who can close it.

**Comment by The-1-7-10-Pack** [comment]
The one who opened this issue can close it aswell. Anyway, happy you got help!
@daytimepanther: Solder may be implemented in the future but currently I can't afford paying for a host.
