### ISSUE TITLE
Pack Crashes when I try rejoining my Single Player Map

### ISSUE THREAD

**Issue by timbo135** [The-1-7-10-Pack/The-1.7.10-Pack#164]
Hey,

First off, thank you for this great modpack and the support, and sorry if my language is not that good, I'm no native speaker.
I played for a few days on my first map testing this modpack. I built quite a lot but suddenly it crashed. It also crashed a few times before (mostly when I clicked an item in the NEI menu) but that wasn't so bad. But when it crashed the last time, i couldn't join my map again. I started a new map, built quite a lot of things again and then it crashed again and now I can not join this map, too.
I really want to go on playing this modpack, but I'm afraid that if i started a new map, this will happen again and everything I had built  was of no earthly use again. 

The last time the game crashed, I think I tried to hook up a ME Import Bus to the Output of a small BigReactors Reactor. (This was already working one time before, so that shouldn't be the thing, but I wanted to let you know though) Now I can still start the game, but when I try to load my map again it crashes.

The latest crashreport, when I tried loading the map again: http://paste.ubuntu.com/10078762/
The latest logfile from the 1.7.10-pack logs folder: http://paste.ubuntu.com/10078786/

If you need anything else, feel free to ask. I hope this helps you as much as me and I hope that you can tell me how to play on my map again.

I'm running Java 1.7.0._67 64-Bit, with 5GB RAM allocated.

AMD FX-8320 Eight-Core Processor 3,50GHz
8,0GB RAM
Windows 7 64-Bit
Asus Radeon R7 265 Series 2GB

Thank you very much for your further help. As I already said, feel free to ask me anything.

**Comment by darktrek** [comment]
hi timbo135, 

i had the same problem with my world with pre made stuff this was the advice i was given below, it worked i had to find every buildcraft thing i had put in the world, from your crash report it looks like a transport pipe that is causing the issue. here is the youtuber that i watched and help me hope it helps 

https://www.youtube.com/watch?v=fWUUsdp3pJ8 

<advice> Because you have the mods information in your world.
It is because some of your mods use an old BC APIs, with MJ power.
I'm sorry but there's nothing you can do about it, I can only recommend you trying to delete the ticking block entity with NBTExplorer. See some guides how on youtube.

**Comment by The-1-7-10-Pack** [comment]
@darktrek 10/10 answer.
