### ISSUE TITLE
I cant join the server ;(

### ISSUE THREAD

**Issue by xXShizzleXx** [The-1-7-10-Pack/The-1.7.10-Pack#170]
a few days ago i tried to join the server, but i got this error: (error2) and when i try to download the light version of this modpack is gives me this error: (error1), so what do i have to do now?

![error1](https://cloud.githubusercontent.com/assets/10907909/6096576/b4a3c856-af98-11e4-919b-49c1ea8871fa.PNG)
![error2](https://cloud.githubusercontent.com/assets/10907909/6096575/a087c584-af98-11e4-842a-7bbb58bff7c3.PNG)

**Comment by The-1-7-10-Pack** [comment]
Unfortunately, The 1.7.10 Pack does not support the MagiTech server anymore, due to the fact that new versions of mods does not support the old version of Cauldron.
If you wish to play in the MagiTech server, you should use the modpack created by Fluke that will work perfectly with the server: http://bit.ly/1Fm0qnP
