### ISSUE TITLE
Id error

### ISSUE THREAD

**Issue by SwaginWagon101** [The-1-7-10-Pack/The-1.7.10-Pack#241]
When Updating my server, I come to this 

http://pastebin.com/raw.php?i=rByzZfYh

i accept and all chised cobblestone and marble become darkleaves. seems like an id error. upgraded from 0.7.2 to 0.7.3

**Comment by SwaginWagon101** [comment]
the chiseld marble and chiseld cobblestone are also microblocks

**Comment by SwaginWagon101** [comment]
it could also be someone on my server, who replaced the blocks...

**Comment by Legomax98** [comment]
All of my microblocks became darkwood leaves (Natura darkwood). I can't figure out why and thats on my single player world, so its not someone else

**Comment by The-1-7-10-Pack** [comment]
@SwaginWagon101, @Legomax98: Can you guys try to help and test [this](http://minecraft.curseforge.com/mc-mods/225236-chisel-2/files/2225497) version of chisel on your servers & clients? Simply switch the version of chisel that is already there with the version I sent you. Tell me what you see.

**Comment by SwaginWagon101** [comment]
After switching to the version you linked me, my client crashed

http://pastebin.com/raw.php?i=qDxBqeGE

**Comment by SwaginWagon101** [comment]
Also on the server, I remade and replaced all of  my chiseled micro blocks, so its still possible to make the blocks.

**Comment by Yorick1234** [comment]
We (running your modpack as server for myself and a few friends for some months now) have the same issue since today, updated to 0.7.3 I alone already have literaly 10 000+ blocks chiseled and sawed to some microblock and placed in my town that now is made of dark wood leaves or invisible item 'Unnamed', and I am not fond of invisible or dark wood leaves strips, panels, covers and such where I used to have nice buildings and tunnels and lightings for my roads and greenery and everything. :( Because theres always crowd online, I cant test your alternative chisel version mod but I will in a few hours and let you know how this turned out.

I really love your modpack and devotion to it, keep it up!

**Comment by Yorick1234** [comment]
I tried using the decompiled Chisel2-2.3.5.31.jar from the link as replacement to Chisel2-2.3.7.34.jar but that made the server crash on startup. So did the compiled version Chisel2-2.3.5.31.jar (taken from server 0.7.2). Probably because I already converted the blocks it by command /fml confirm during first startup. I also tried all the other available versions of chisel2 from curse.com/mc-mods/minecraft/225236-chisel-2 but they either crashed during startup (the older ones) or did startup (I had to replace both client and server installed version) but the issue continued by the showing of dark wood leaves. I'm now running Chisel2-2.3.7.34.jar again, and simply wait for a solution. I am able to build new chiseled microblocks that seem to keep their correct material, but I'm not yet mentally ready to replace my existing 10 000+ blocks.

**Comment by The-1-7-10-Pack** [comment]
@SwaginWagon101, @Legomax98, @Yorick1234: Weird. If you guys open a new world everything is just fine?

**Comment by SwaginWagon101** [comment]
I believe this is the full log here https://drive.google.com/file/d/0Bwz0nxShRWqkMzliZENneFBrVzQ/view?usp=sharing

Also It crashes before I even get to the main menu. And I am not using sphax.

**Comment by The-1-7-10-Pack** [comment]
@SwaginWagon101: No, I wish to get the log that launches (with the latest version of Chisel 2) but with the ID Problem as you say.

**Comment by Yorick1234** [comment]
I have it here:

https://drive.google.com/folderview?id=0B378CPa7-4bRMFVTOFo2UUwwclU&usp=sharing

**Comment by The-1-7-10-Pack** [comment]
@Yorick1234: A random guess; try to add [this](http://minecraft.curseforge.com/mc-mods/222784-chisel-facades/files/2225507) mod to the server (and client) and see if anything changes.

**Comment by The-1-7-10-Pack** [comment]
@Yorick1234; @SwaginWagon101; @Legomax98; Anyone can help?

**Comment by SwaginWagon101** [comment]
Sorry I've been a little busy lately.  I'll do it when I get home later today.

**Comment by The-1-7-10-Pack** [comment]
@SwaginWagon101, @Legomax98, @Yorick1234:
Well I've checked it myself and it didn't work.
I guess that it's a problem from chisel's side when we updated chisel.
It's not THAT big of a deal and I hope that you guys will be able to understand.
Not in my control, next time that there will be a chisel update I'll check for it again.

**Comment by Yorick1234** [comment]
Sorry for the late response. I deleted my blocks and am still in the process or placing new ones. I will try the ChiselFacades mod and see what it does.

**Comment by Yorick1234** [comment]
That had no effect. But I've accepted the fact the old blocks are definitely lost and had to be replaced. Thanks for all the effort helping me.

**Comment by The-1-7-10-Pack** [comment]
:)

**Comment by GreatHolyCow** [comment]
Please next time make sure blockids dont dramatically change like that with out warning

**Comment by The-1-7-10-Pack** [comment]
@GreatHolyCow It's not in my control and I can't check for each and each block evey update. Although, I don't think it will occur again because we removed Chisel Facades just once, and I think that Chisel 2 will take care of the rest.
Also it's not that critical, it's not like all of your nether stars turned into eggs :)

**Comment by The-1-7-10-Pack** [comment]
Worth to note that this problem happened in [every singel modpack](http://forum.feed-the-beast.com/threads/1-1-0-1-0-3-to-1-1-1-multiple-chisel-microblocks-tesseract-fps-lag-links.69335/) that includes Chisel 2.

**Comment by SwaginWagon101** [comment]
Understood.  I know it's not your fault.  I  appreciate you taking the time to help us.

**Comment by The-1-7-10-Pack** [comment]
This bug may happen again with the move to v0.7.6 as the Chisel 2 mod has updated and it has unexpected things coming with it.

**Comment by Legomax98** [comment]
Now that Github is done being DDoS'd, it seems that all textures are working fine. I'm not having any problems.
