### ISSUE TITLE
Random Things

### ISSUE THREAD

**Issue by alex2710xela** [The-1-7-10-Pack/The-1.7.10-Pack#247]
https://randomthingsminecraftmod.wikispaces.com/

I think this would be a good addition. It isn't an overpowered mod. It adds a bunch a useful things. Its also adds a spectre key which is a great place to store items and me systems.

**Comment by GamerMan7799** [comment]
I agree, was think about adding this myself.

**Comment by Torterra** [comment]
great idea, this would be a great addition to this pack!

**Comment by martinegui** [comment]
this mod would be a really great adiction to this modpack, blood moon would be really funny and challanging!

**Comment by liquid-metal** [comment]
i agree!

**Comment by TreePuncher9501** [comment]
Seems good in my opinion.

**Comment by The-1-7-10-Pack** [comment]
To really know what should I think about this suggestion, I'd ask you guys to note me the 3 best mechanics in Random Things that other mods can't provide.
@alex2710xela, @GamerMan7799, @Torterra, @martinegui, @liquid-metal.

**Comment by GamerMan7799** [comment]
I personally really like the blood moon because it causes a lot of panic when i happens, it raises the mob cap and causes a lot of mobs to spawn. If you don't locked yourself underground or in your house you are basically dead, a lot.

I also really like the spectre key, it gives everyone access to their own personal space that they can go to from anywhere. Its a 14x10x14 box that you cannot expand and that only admins can access besides you. Its great for storing important stuff away where no one can access it. 

The ender letter is also useful as you can send someone items even if they are not online.

The mod adds a lot more than this but this is what I think are the most useful features. 

A quick note this mod has its own fast leaf decay so you might need to remove the other leaf decay mod or disable it here, it depends on which one you like better I guess.

**Comment by alex2710xela** [comment]
@The-1-7-10-Pack  I think we should add this because of Spectre world which adds a private bubble for every one. It also adds a blood moon which adds a real challenge to the night. One more of many things it adds is the linking orb. The Linking Orb allows you to connect your life points to those of other entitys. I hope you add this mod, it has a lot to offer and its very useful stuff.

**Comment by CriticalRocket** [comment]
I hope the mod is configurable.

Whilst I know why you all like the spectre key, public server owners might not always like it. 
I can think of more than enough reasons to not give everyone a private box.
- is every box a new dimension? -> Lagg
-Every box saved somewhere in the world -> takes up a big part of the world
-PvP/Faction server -> you dont want people to have 100% of their items.

And if you're only playing with friends, you dont need a private place anyway.

Ender letter:
You've got chests, don't you?..

Blood moon:
Sounds interesting/like fun. Copied from Terraria :p but that doesn't really matter. 

Chat detector: Block that outputs a redstone signal when something is typed by a specific player in chat. Sounds amazing :D 

Gintos: sould drops after death, other player can revive you with a certain item.
Could cause problems with the gravestone mod, either duping your items on deat/revival or causing a crash.

Hardcore darkness: literally 0 lighting instead of minecraft default in which there's always little bit of light: I really like this idea, screenshots look awesome.

Some features I like, some feature's I don't really care about cause they are useless to me/some things I think can cause problems. 

Still, more mods is more drag on your computer, and is this mod worth that?
The functions I like (hardcore darkness, blood moon and stuff) are worth it for me, but only if I can turn certain other things off. I don't want my sneaky friends creating secret rooms hoarding items :p

**Comment by alex2710xela** [comment]
Every box is not another dimension, if you don't believe me watch the series mianite, you can see other people's boxes from your own box. It's all in the same world, it's just others can't get to your box.

**Comment by The-1-7-10-Pack** [comment]
We'll currently won't add the mod. It doesn't really fit the pack, and it's too big. Although some of the things the mod provide such as the bloodmoon is cool and not that heavy, some other things are not like that. Thanks anyway for suggesting.
