### ISSUE TITLE
dimension problem

### ISSUE THREAD

**Issue by bennygeorgiev** [The-1-7-10-Pack/The-1.7.10-Pack#276]
i have a problem in my server, when there is no player in specific dimension the server not loading the dimension even if there is a chunk loader or world anchor it not loading it and portals aren't working 

HELP

**Comment by The-1-7-10-Pack** [comment]
How do you know that it doesn't load?

**Comment by bennygeorgiev** [comment]
because when i put a digital miner or teleporter  it stops in the second i leave the dimension they stop working
example: i made teleporter to the moon and it stopped when i leaved the dimension the same with the digital miner

**Comment by The-1-7-10-Pack** [comment]
And you putted a chunk loader there?

**Comment by Spellkaze** [comment]
I have the solution to this, the galacticraft mod have a different way to load chunks, so try this. (This only work in any galacticraft dimension)

1. Go to the moon / space station / mars or asteroids dimension
2. Once you are in the dimension, use /gckeeploaded
3. It should show a message: "Successfully set dimension X to load staticly" if it says "not load staticly", try the command again, use OP if neccesary.
4. Once you have done that, put a Chunk loader in the same chunk that the Teleporter and the Digital miner are.
5. Even if you shut down the server, when you loaded it again, everything should be fine.

*** The chunk loader near the teleporter is VERY IMPORTANT!, otherwise this would not work and you should have to use a rocket again!

Something like this! http://i.imgur.com/8ET32FA.png

**Comment by bennygeorgiev** [comment]
thanks but what about the nether?
it not loading the digital miner there too even with chunk loader

**Comment by The-1-7-10-Pack** [comment]
I've tried it myself and nothing is wrong, my quarry works great in the nether with the chunk loader. You're probably just doing something wrong. What chunk loader are you using?

**Comment by Spellkaze** [comment]
Well, I triedd this:
1. In the nether use /gckeeploaded 
2. Put a ChickenChunks' Chunk Loader with at least 3 or 4 of radius.

It should work now, it takes a bit of time before it works, I recommend you to use a pipe for transporting the items out of the digital miner (itemduct pipe from Thermal Dynamics should be fine) connect it to a Tessract in the nether and connect it with a chest to the overworld with another Tessract.

Also, remember to have a chunk loader in your energy output (if you have one), probably is not taking energy correctly and that's why is not working

At least it worked, it took some time to the digital miner to actually works in my world.

**Comment by bennygeorgiev** [comment]
i mean when i close and open the server it not loading the dimension and nothing works there
and i used all the chunk loaders in this pack.
i looked in the server log and after it loads the world it writes "Unloading dimension....."
i realy don't know why it happends

**Comment by The-1-7-10-Pack** [comment]
Oh, no. You got to load the chunk loader first and then it will keep it loading. Just when you open the server go to your chunk loader dimension and then it will keep loaded.

**Comment by bennygeorgiev** [comment]
yes but then when i close the server and open it, the server again not loading the dimension

**Comment by bennygeorgiev** [comment]
and it realy hard to get all the fuel to the spaceship

**Comment by The-1-7-10-Pack** [comment]
Well it's not a problem and it's also nothing specific about the modpack.
I'm not sure that there's a way to do what you want to do. You should ask about it on somewhere big about modding, maybe on the FTB subreddit.

**Comment by bennygeorgiev** [comment]
the cheat of galactic craft worked thanks a lot

**Comment by The-1-7-10-Pack** [comment]
Happy to see that other people helped you, thanks @Spellkaze!
