### ISSUE TITLE
Any way to get the server work with bukkit plugins?

### ISSUE THREAD

**Issue by micronax** [The-1-7-10-Pack/The-1.7.10-Pack#31]

**Comment by chrisps89** [comment]
I have no idea, off the top off my head I would have said no because most of the mods on the server run on forge but https://www.beastnode.com/portal/knowledgebase/101/Install-BukkitForge-or-MCPCplus-or-Cauldron.html May be worth looking into, although I have no idea how it works or if it works, I just found it on google.

**Comment by Flukethoughts** [comment]
If you keep update on how things work all those options are dead.
