### ISSUE TITLE
Mystcraft

### ISSUE THREAD

**Issue by The-1-7-10-Pack** [The-1-7-10-Pack/The-1.7.10-Pack#403]
What are you saying guys? :)
There are permissions.

**Comment by ChinesePeanuts** [comment]
I think it can be nice ! Interesting mod

**Comment by Deathwinng** [comment]
It would be cool to have Mystcraft in the modpack!

**Comment by betzholz** [comment]
! pro i played it on an other mod pack after switching i missed it much... so please please :)

**Comment by Canuck117** [comment]
More dimensions more fun.  Yes, please.

**Comment by Boehrsi** [comment]
+1 definitely :)

**Comment by Neology2k** [comment]
I'd love this too to be fair..

**Comment by GroeneAppel** [comment]
I already have mystcraft on my server as extra addition to the pack, as it's one of my favorite mods. But please beware of the harsh strain this mod puts on the server. In addition i've already encountered serveral crashes due to Mystcraft. That said, the recent patches claim to all be improving performance.

**Comment by Nogotogon** [comment]
Mystcraft is awesome my dad used to make his own mod packs before he found out about Technic and second to Aether, mystcraft was my favorite
