### ISSUE TITLE
The 1.7.10 Pack Won't Launch On Mac OSX

### ISSUE THREAD

**Issue by Hypolex** [The-1-7-10-Pack/The-1.7.10-Pack#501]
For Some Reason The 1.7.10 Pack won't launch on Mac OS X Please Help Me Out 

Hypolex :D

**Comment by The-1-7-10-Pack** [comment]
Please post your latest launcher log using a [paste-tool](http://paste.ubuntu.com/), thanks.

**Comment by Hypolex** [comment]
What Is A Launcher Log??

**Comment by Hypolex** [comment]
Where Do I Copy The Launcher Log? :D

**Comment by CriticalRocket** [comment]
Search for the Technic folder. Inside that foldere there's a folder called logs. In there are all launcher.logs :)

**Comment by rubesthefrube** [comment]
Its the same for me :/ 
Log: http://pastebin.com/C9sLaxNY

**Comment by The-1-7-10-Pack** [comment]
@rubesthefrube You're using Java 6, this is your problem :)

**Comment by rubesthefrube** [comment]
Whats the recommended Java version ??? latest?

**Comment by The-1-7-10-Pack** [comment]
@rubesthefrube Java 1.8. 1.7 would work, but 1.8 is the recommended. Yours, 1.6, won't work at all.

**Comment by rubesthefrube** [comment]
Well theres a major mac bug in the technic launcher, it automatically runs Java 6 no matter version of Java you have on our mac. This is why I was confused to the launcher not working. Although some modpacks still support Java 6, most don't including your 1.7.10 Modpack. After 2 hours of messing around with different versions of Java, i've finally found a solution to all mac users XD.

1)Install a Java SE Development Kit, rather than the normal SE edtion which most users choose. (I will leave a link below)  However, DO NOT USE DEMOS & SAMPLES

2) Click Mac OS X x64 tab (Under Development Kit 8u45) and download.

3) Go through the steps to installing this version on your mac.

4) Open Technic Launcher and click Launcher Options. Inside go onto Java Settings and it should automatically now say "Default (1.8.0_45 64-Bit)". If not click on the drop down box to find this.

Now, all of the modpacks on technic will work, including The 1.7.10 Modpack!!

Link: http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html

PLEASE REMEMBER USE  Java SE Development Kit 8u45 and NOT  Java SE Development Kit 8u45 Demos and Samples Downloads otherwise it wont work! 

Hope this helps!
-Rubes

**Comment by The-1-7-10-Pack** [comment]
^
Closing this one :)

**Comment by Hypolex** [comment]
Do I Need To Do This On Windows As Well ?

**Comment by The-1-7-10-Pack** [comment]
@Hypolex On windows you also need the right version of Java, of course. Just don't worry about the launcher finding it, should be easy. Just be sure it's installed.
