### ISSUE TITLE
Lag with mega rubber tree

### ISSUE THREAD

**Issue by Nogotogon** [The-1-7-10-Pack/The-1.7.10-Pack#521]
When i try to mine the mega rubber tree with and ax the game starts lagging like crazy does anyone know anything?

**Comment by CriticalRocket** [comment]
You are aware that when you chop down a tree with an axe the whole tree gets chopped down right? 
All wood, saplings and apples from that tree then drop. 

When you chop down a huge tree, the game has to proces 100's of block changes and drops in a fraction of a second, which requires a lot of processing power,

Don't chop down huge trees with axes, you'll need to use your hands, or an atomic dissasembler, because I've noticed the atomic dissasembler doesn't chop down a whole tree at once. There may be more items you could use :)

Another option is trying to mine the tree with an axe which has a very low durability. Because when you mine a tree, it will cost you the durability of all wood blocks in that tree. When you don't have enough durability to mine the whole tree only a part of the tree will be chopped down, and your axe will get destroyed. But since only a part of the tree gets mined at once it doesnt cause as much strain on your processor.

**Comment by The-1-7-10-Pack** [comment]
^
I can't do anything about it.

**Comment by Nogotogon** [comment]
yea i have been doing that but... i mined down one of the giant trees from thaumcraft and everything went fine... mabie it was smaller.
