### ISSUE TITLE
Personal Server Help

### ISSUE THREAD

**Issue by PersonalServerHelp** [The-1-7-10-Pack/The-1.7.10-Pack#538]
I'm trying to host a personal server through Hamachi. I go into the server properties file and set the ip = to my hamachi ip. After i do that, the server crashes. I can run the server fine if I leave the settings for ip blank. Any ideas on how to get this fixed?

**Comment by PersonalServerHelp** [comment]
I get this error when i try to launch the bat as an admin "
Error: UNable to access jarfile forge-1.7.10-10.12.2.1352-1.7.10-universal.jar

I don't get that error if I leave the ip blank.

**Comment by CriticalRocket** [comment]
You don't have to fill in anything in the 'ip=' section of the properties file. Well, more like, you HAVE to leave it blank!

If you want to run a server through hamachi:

1. Start hamachi.
2. Create a network on hamachi.
3. Let the people you want to play with join your hamachi network.
4. Start your minecraft server
    +leave the server properties 'ip=' empty
5. Other people have to connect using your hamachi ip4 adress
    + Go to hamachi
    + Look at your own computer in your network
    + right click it, and click 'copy ip4' adress (you can also view it and type it over, its visible behind the name of your computer)
    + Open your minecraft client
    + Go to 'multiplayer' and simply enter the ip4 adress to connect.
6. If you yourself want to join, use the ip4 adress or type ''LocalHost' instead of an ip adress
    -NOTE: Because the server is hosted on your own computer, you don't need to know the ip to connect. You yourself can join with 'LocalHost'.

And then it's done! :)


NOTE: You can create a network of 5 people max on hamachi without having to pay, you can, however, create multiple networks. As long as everyone is in a network with your it's fine, so just create more networks if you want more people to join (not 100% sure that works, but it should I think :p)

**Comment by The-1-7-10-Pack** [comment]
^
Thanks for helping @CriticalRocket!
