### ISSUE TITLE
Modpack Wont Open 

### ISSUE THREAD

**Issue by debtbringer** [The-1-7-10-Pack/The-1.7.10-Pack#555]
A friend of mine has downloaded this mod pack and it won't open (we hit launch on the technic launcher the launcher then disappears and reappears after a few moments) I have tried uninstalling and re installing java and Technic as well as the mod pack itself. Thank you for any help in advance.
 
Crash report:http://pastebin.com/3qMZjihM

**Comment by mckulich** [comment]
Hi, i have similar problem with Attack of B-team mod pack, just like you say, i press start button and the launcher then disappears and reappears after a few moments. I have Java version 8 and this mod doesnt supported it. so i must update my old modpack to ne version and after everything was fine.

So i suppose that in your case you need update your java version to version 7/8. I am not 100% sure, because i am not expert but crash report says at least 3 or 4 times something about unsupported java version 
Like :"[15:26:21] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:461]: java.lang.UnsupportedClassVersionError: ivorius/ivtoolkit/IvToolkitLoadingPlugin : Unsupported major.minor version 51.0"

**Comment by The-1-7-10-Pack** [comment]
@debtbringer You have Java 6, The modpack requires Java 7/8 64 bit.

**Comment by debtbringer** [comment]
Okay so I updated java and now it will open up for a second but the immediately close again. the crash log says: 
"[21:42:08] [main/DEBUG] [FML/]: Instantiating coremod class CodeChickenCorePlugin
[21:42:08] [main/WARN] [FML/]: The coremod codechicken.core.launch.CodeChickenCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft"


Full crash log: http://pastebin.com/Zj8B6Cm8

**Comment by The-1-7-10-Pack** [comment]
@debtbringer You're still on Java 6..Uninstall and install again Java 8..
