### ISSUE TITLE
Twilight Forest

### ISSUE THREAD

**Issue by ZekAttack** [The-1-7-10-Pack/The-1.7.10-Pack#559]
So once I entered the twilight forest there was the rain that hurts you telling you that you cannot be in that are as well as the slowing snow surrounding my portal. Is this intentional or a bug.

**Comment by The-1-7-10-Pack** [comment]
Wha? Can you be more clear?

**Comment by ZekAttack** [comment]
what happened was that once i entered the twilight forest i could not do anything as i was surrounded by elements that required me to beat another biome toaccess it

**Comment by mckulich** [comment]
It could be one from special effects in TF (Twilight Forest). Some biome makes you extremly hungry, some burn you to death, so you probably have bad luck and your portal was spawn on the bad place :D

**Comment by CriticalRocket** [comment]
The location of your portal in the forest is linked to the location of your portal in the overworld, just like with nether portals. Try walking a bit in the overworld and making a new portal a bit further away :)

(I'd cheat back my diamond since this isn't really supposed to happen and its a shame of a diamond :(  )

**Comment by The-1-7-10-Pack** [comment]
Closed due to inactivity.
