### ISSUE TITLE
Game Crashes on Startup

### ISSUE THREAD

**Issue by sKaNoN** [The-1-7-10-Pack/The-1.7.10-Pack#570]
Whenever i try to Launch the Modpack it crashes instantly.
Tried it with the versions 0.7.6c and 0.7.7a, both have the same problem.

OS: Windows 8.1 (64-bit)
Java: 8u45 (64-bit)
Crashlog: http://pastebin.com/NgexvkxB

---
Addition: i tried reinstalling Java (latest V7 and V8) and the Modpack itself, neither helped

**Comment by The-1-7-10-Pack** [comment]
OpenComputers downloaded it's lib files wrong, try to backup your saves and completely delete the modpack's folder. Then try to install again. If it doesn't work, go to [OpenComputers's GitHub page](https://github.com/MightyPirates/OpenComputers/issues) for help, because it's really not the modpack but the mod's fault.
