### ISSUE TITLE
GrowthCraft is outdated to the latest Forge updates, crashing

### ISSUE THREAD

**Issue by Ceritus** [The-1-7-10-Pack/The-1.7.10-Pack#583]
http://paste.ubuntu.com/11177296/
Right clicked on brew kettle and CTD twice

**Comment by The-1-7-10-Pack** [comment]
That's bad. Growrthcraft didn't update to the latest Forge chanegs with the fluids, so it just crashes. I'll try to contact the author to understand his future plans. If the mod won't update, we'll have to remove it.

**Comment by Ceritus** [comment]
i will just remove the celler part till its updated

**Comment by mckulich** [comment]
i can confirm same problem :) 
http://paste.ubuntu.com/11680476/

**Comment by egclark17** [comment]
I'm having the same problem with the fermentation barrel.

**Comment by The-1-7-10-Pack** [comment]
So guys, think we should remove GrowthCraft, or wait for a fix?

**Comment by Ceritus** [comment]
i removed the cellar part of the mod the rest seems fine

**Comment by The-1-7-10-Pack** [comment]
@Ceritus We can't know what else is problematic and we can't really check the whole mod for fluids. Currently will keep the mod, may remove other parts later.

**Comment by mckulich** [comment]
it is fine, actually i dont even use Growcraft, so we can keep the mod in pack and wait for fix ;)

**Comment by retrozool** [comment]
Just remove Growthcraft until it gets fixed - according to http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1286298-growthcraft-jul-15-2014-proper-1-7-10-release?comment=2073 someone reached the author and he's no longer interested in the mod an wants the community to fix it
It's just annoying when your game crashes just because you (again) clicked on a barrel in a village.

**Comment by The-1-7-10-Pack** [comment]
"shortybsd" has released a fix :)
