### ISSUE TITLE
Another Crash

### ISSUE THREAD

**Issue by Alexander175** [The-1-7-10-Pack/The-1.7.10-Pack#65]
So i was on the server and i was scanning a common hive with my thaumomicain and i crashed also this has happened with other things.

Log https://www.dropbox.com/s/tjbuf1agijm2tb1/latest.log?dl=1

Crash Report: http://paste.ubuntu.com/9721848/

**Comment by The-1-7-10-Pack** [comment]
That is a very intresting but may I say. The Ticking entity is actually you! yep.
Something to do with Thaumcraft, ComputerCraft & a bit of Galacticraft (thus, GC makes the player entity diffrent, and if the entity is the problem..yeah.)
But because the crash happened using Thaumcraft items I'd recommend you reporting the crash there: https://github.com/Azanor/thaumcraft/issues
Be sure to give there all the information you got and the crash-report link I edited to your comment.
