### ISSUE TITLE
Modpack Suggestions

### ISSUE THREAD

**Issue by skohlhepp** [The-1-7-10-Pack/The-1.7.10-Pack#663]
So I have been running a 1.7.10 pack server for a few weeks now and I am happy to announce that we are the top ranked 1.7.10 Pack server in the world! Not only that, but we are ranked 10th in the world out of all technic pack servers currently. 
![screen shot 2015-06-11 at 1 40 39 pm](https://cloud.githubusercontent.com/assets/6201112/8139740/107e7dc8-1124-11e5-8f80-80398b3b17bd.png)

Now I am not writing this post to brag, but you can connect with blackwood.beastmc.com (Running 0.7.7b)

I am writing to convey some things that have been asked about a lot on the server so far and also report a few dupe glitches among other issues that we have encountered. 

Firstly, many people have had issues with portals to places like the mining world not working. Yes this could and probably is something to do with the server setup but we have come up with a few workarounds, I just wanted to see if any other servers were having similar issues. 

Dupe Glitches:
Uncrafting Table (Can dupe any item with more than 1 recipe)
Block Breaker and Placer
Dolley's
MFR spawner can spawn robits which have an inventory
Luggage can also be spawned in the MFR Spawner
And a few more that I can't remember off the top of my head. 

Personally, I would ask that a few mods be cut from the pack in the next update such as fastcraft and NotEnoughResources and colorchat, all incompatible with Cauldron. Additionally, there are a few other seemingly pointless mods lying around in the pack that no one ever uses and for the sake of performance I think that they should be cut. Obviously it's not my pack nor my decision but..

Anyway thanks guys,

Sko

**Comment by The-1-7-10-Pack** [comment]
* Portals: Never heard of such problem, probably just people unaware to the fact that they need to sneak while entering the Mining Dimension portal for it to work.

* Dupe glitches: Some glitches are unavoidable, and they are not caused by the modpack but caused by the actual mods. Others you mentioned here but didn't say how to actual dupe, so I'd like to hear that.

* Cutting mods out: The modpack is not built for Cauldron, and doesn't have any official Cauldron support. The pack has built before Cauldron was a thing, although I'm very happy it's back again with updates and support. When a server owner wants to install Cauldron he can very easily cut those mods out, when a normal group of players want to have fun, they can still enjoy other mods. Removing mods also don't give more performance that easily; ColorChat and NotEnoughResources are so small, not to mention that FastCraft just helps performance. No mod is going to be removed, but thanks for the feedback.

**Comment by The-1-7-10-Pack** [comment]
Closed due to inactivity.
