### ISSUE TITLE
Crashing? 

### ISSUE THREAD

**Issue by RedGoblin** [The-1-7-10-Pack/The-1.7.10-Pack#681]
Not sure if it's my server or whatnot. 

But getting errors when I go into the nether.
 Yet when my friend does it, it doesn't crash the server.

**EDITED: Please use a paste-tool: http://pastebin.com/vtGPk4nt**

**Comment by The-1-7-10-Pack** [comment]
It has something to do with an EnderIO monitor connected to a Mekanism cable.
You have a ticking entity that you need to delete using NBTExplorer, see a guide [here](https://www.youtube.com/watch?v=fWUUsdp3pJ8).
The crash is caused due to something with EnderIO and/or Mekanism, should be reported in their repos :)
