### ISSUE TITLE
5 mods that would fit in the mod pack surgestion 

### ISSUE THREAD

**Issue by darktrek** [The-1-7-10-Pack/The-1.7.10-Pack#73]
the secret room mod

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1276042-v4-6-3-v4-7-0-alpha-secretroomsmod-hidden-trapped

This mod adds a variety of cool blocks that camouflage themselves to the surrounding world. All of these blocks have extremely useful functions that allow you to simply hide your diamonds, or punish all who dare try to get to them.

invisible lights mod

http://minecraft.curseforge.com/mc-mods/222830-invisiblights

Most Minecraft players have already stumbled over this problem: keeping something well-lit requires an extraordinary large amount of Torches or other light sources. The result is a scene jammed with those. As the title suggests, this mod adds light sources that can be completely hidden.

flaxbeard steam power 

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2246930-flaxbeards-steam-power-beta-0-27-3-updated-dec-23#c3

Flaxbeard's Steam Power (FSP) is a tech mod based on steam power at its core.

fossils and archeology

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1288066-fossils-and-archeology-revival-build-7-0-1

ars magica 2 ( when more stable) 

i think all these would work and flesh out the adventure section of your mod :)

**Comment by KLuebbert** [comment]
Flaxbeard's Steam Power is an interesting mod that keeps reappearing in many packs I play. I usually end up using it, but not going far. I would like to use it more, and learn more about it, and it's pretty fun. I agree with it being in the pack.

The Secret Rooms mod is also cool, I like using it for secret rooms for my blood magic and stuff, so that's another good idea.

The invisible lighting seems cool too, but I disagree with the Archeology mod, adding dinosaurs doesn't seem to fit, even though I know it adds a few other things. I'm a little unsure about Ars Magica, however.

**Comment by The-1-7-10-Pack** [comment]
I simply can not explain why for each mod but I can't add all of those mods, maybe only Ars Magica 2 when it'll be more stable. Thank you anyway for the suggestions!
