### ISSUE TITLE
Game won't open

### ISSUE THREAD

**Issue by holigan35** [The-1-7-10-Pack/The-1.7.10-Pack#755]
I can't open it.I press play but It won't open.I have java 7/8 64 bit.And here is log
http://pastebin.com/wnzkJWMT Help please

**Comment by The-1-7-10-Pack** [comment]
That's a libaries problem. Try to reinstall the launcher and it'd fix it. :)
If it wouldn't, I'll reopen the issue.

**Comment by holigan35** [comment]
It wouldn't fix it now here it is pastebin.com/51fy4Kub

**Comment by skittishtrigger** [comment]
Looks like you need the full log for one. Out of curiosity since you said you have 7/8 jre versions have you selected the version you want to use in launcher options? running dual versions also sometimes requires you to make sure you set it in the environment variable path. 

quick link to do so:
https://docs.oracle.com/javase/tutorial/essential/environment/paths.html

From what I can tell THERE IS missing info in that log. make sure you are getting the whole thing when posting. to bypass the log size issue with pastebin use:
http://paste.ubuntu.com/

The more info there the easier it is to find/fix an issue.

**Comment by The-1-7-10-Pack** [comment]
@holigan35 If you gave us the launcher log now, try to give the client log. It can be found in:
> .technic/modpacks/the-1710-pack/logs/fml-client.latest.log

Indeed use [this](http://paste.ubuntu.com/) paste-tool for it, because it might be big.

**Comment by The-1-7-10-Pack** [comment]
Closed due to missing information.
