### ISSUE TITLE
crash when trying to add sphax resourcepacks 

### ISSUE THREAD

**Issue by darktrek** [The-1-7-10-Pack/The-1.7.10-Pack#90]
here is the complete crash log i get every time i go resource packs and add them 

http://pastebin.com/hpkPeCvf

**Comment by The-1-7-10-Pack** [comment]
You are out of memory. How Much RAM do you have installed on your computer?
Also what version of the resource pack did you download?

**Comment by darktrek** [comment]
my computer has 16 gb of ram and i downloaded Sphax PureBDcraft 128x MC17.zip, 
Sphax The 1.7.10 Pack 128x.zip also i have downloaded and tried the 64x for both packs and still get the error

**Comment by The-1-7-10-Pack** [comment]
It make no sense. It shouldn't happen with the 64x version. Is the 32x version works?

**Comment by darktrek** [comment]
the 32x versions work i have installed and played with them on

**Comment by The-1-7-10-Pack** [comment]
64x version should also work. Do you have any custom Java settings on your computer?

**Comment by darktrek** [comment]
not that i am aware of i have not done anything myself i just click the technic launcher and load the mod pack,

**Comment by The-1-7-10-Pack** [comment]
Do you have any additional mods?

**Comment by darktrek** [comment]
yes 20 but i dont see how that can be the issue since my current texture pack is 128x that i was using before Sphax brought theres out. old pack was Chroma Hills Ver:1.0.11 LATEST 128x

**Comment by The-1-7-10-Pack** [comment]
Sphax takes more memory, also I am not sure how many mods your resource pack supported.
The modpack uses automatically RAM up to 3 GB maximum. You probably used more than that, with your mods. If you wish to change that, and I recommend you that (because you have 16): Go to the modpacks folder, bin/version.json and change the -Xmx3072M to how much you want. Do the same for the version.json that is in the modpack.jar.

**Comment by Flukethoughts** [comment]
I would suggest not hardcoding the pack anymore. Let users decide how much ram they want to use.
