### ISSUE TITLE
Crashes Immediately, No Crash Log

### ISSUE THREAD

**Issue by NitsuaRevaew** [The-1-7-10-Pack/The-1.7.10-Pack#98]
I know this sound very vague, but I can't get any more specific. I just installed the pack for the first time through the technic launcher. When it starts up it immediately crashes. I cannot find the crash log anywhere in the .technic folder. Any help? Thanks

**Comment by Flukethoughts** [comment]
is your computer plugged in?







Ok have you had this issue with any other modpack?

**Comment by NitsuaRevaew** [comment]
Yeah, a few others like Hack/Mine dont work, but some others do

**Comment by Flukethoughts** [comment]
the ones that dont work are they a certain version of mine craft?

**Comment by The-1-7-10-Pack** [comment]
Please provide the latest launcher log.

**Comment by huxli** [comment]
ive been having the same problem i just noticed i have java 8 so im uninstalling it and downloading java 7 because java 8 has caused problems previously on other mod packs maybe check if your running java 8 if so uninstall and find the latest java 7 version  ill get back and see if this fixes the problem

**Comment by The-1-7-10-Pack** [comment]
@huxli Not all the problems in the world caused by Java 8. I'd hope so though, Uninstall Java 8 on the middle east and install Java 7.
It can be a RAM issue too, Java 32bit can be bad.
I need the launcher log to help

**Comment by The-1-7-10-Pack** [comment]
Closed due to missing information.
